<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */

function ssu_schedule_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.ssu_schedule':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text);
      }
  }
  return NULL;
}

function ssu_schedule_theme() {
  return [
    'schedule_page' => [
      'variables' => [
        'faculties' => '',
        'college' => '',
      ],
    ],
    'test' => [
      'variables' => [
        'test1' => '',
      ],
    ],
  ];
}
